//! Browser sign-in for Nexus Mods (their "SSO" flow).
//!
//! This is the flow Vortex and the official Nexus Mods App use, and it saves the
//! user from copying an API key by hand:
//!
//! 1. open a websocket to `wss://sso.nexusmods.com`
//! 2. send a request carrying a client-generated UUID
//! 3. the server replies with a connection token, which is cached so a later
//!    reconnect resumes the same session
//! 4. open `https://www.nexusmods.com/sso?id=<uuid>&application=<slug>` in the
//!    browser, where the user approves
//! 5. the server pushes an API key down the same socket
//!
//! # The catch
//!
//! Step 4 needs an application slug, and Nexus documents that
//! "an application reference can only be generated by Nexus Mods staff".
//! A third party cannot mint one. Until Apocrypha is issued a slug, this flow
//! cannot complete, which is exactly why pasting a personal API key remains a
//! first-class option rather than a fallback bolted on afterwards.

use serde::{Deserialize, Serialize};
use std::time::{Duration, Instant};
use thiserror::Error;

const SSO_WS: &str = "wss://sso.nexusmods.com";
const SSO_PAGE: &str = "https://www.nexusmods.com/sso";

/// How long to wait for the user to approve in their browser.
pub const APPROVAL_TIMEOUT: Duration = Duration::from_secs(300);

#[derive(Debug, Error)]
pub enum SsoError {
    #[error("could not reach the Nexus Mods sign-in service: {0}")]
    Connect(String),
    #[error("the sign-in service sent something unexpected: {0}")]
    Protocol(String),
    #[error("Nexus Mods rejected the sign-in request: {0}")]
    Rejected(String),
    #[error(
        "Apocrypha has not been issued an application id by Nexus Mods yet, so browser \
         sign-in cannot be used. Paste a personal API key instead."
    )]
    NoApplicationSlug,
    #[error("sign-in timed out. Nothing was changed.")]
    TimedOut,
}

#[derive(Debug, Serialize)]
struct SsoRequest<'a> {
    id: &'a str,
    token: Option<&'a str>,
    protocol: u8,
}

#[derive(Debug, Deserialize)]
struct SsoResponse {
    #[serde(default)]
    success: bool,
    #[serde(default)]
    data: Option<SsoData>,
    #[serde(default)]
    error: Option<String>,
}

#[derive(Debug, Deserialize)]
struct SsoData {
    #[serde(default)]
    connection_token: Option<String>,
    #[serde(default)]
    api_key: Option<String>,
}

/// Progress callbacks, so the caller can drive a UI without this module knowing
/// anything about one.
pub trait SsoObserver {
    /// The user must now approve in their browser at this URL.
    fn awaiting_approval(&self, url: &str);
}

/// Generate a version 4 UUID from system randomness.
fn uuid_v4() -> String {
    let mut bytes = [0u8; 16];
    getrandom(&mut bytes);
    bytes[6] = (bytes[6] & 0x0f) | 0x40; // version 4
    bytes[8] = (bytes[8] & 0x3f) | 0x80; // RFC 4122 variant
    let h: Vec<String> = bytes.iter().map(|b| format!("{b:02x}")).collect();
    format!(
        "{}-{}-{}-{}-{}",
        h[0..4].concat(),
        h[4..6].concat(),
        h[6..8].concat(),
        h[8..10].concat(),
        h[10..16].concat()
    )
}

fn getrandom(buf: &mut [u8]) {
    use std::io::Read;
    if let Ok(mut f) = std::fs::File::open("/dev/urandom") {
        if f.read_exact(buf).is_ok() {
            return;
        }
    }
    // Falling back to the clock is weaker, but a failure to open /dev/urandom
    // should not turn sign-in into a hard error.
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    for (i, b) in buf.iter_mut().enumerate() {
        *b = ((nanos >> ((i % 16) * 8)) & 0xff) as u8;
    }
}

/// The page the user approves on.
pub fn approval_url(uuid: &str, slug: &str) -> String {
    format!("{SSO_PAGE}?id={uuid}&application={slug}")
}

/// Result of a completed sign-in.
#[derive(Debug, Clone)]
pub struct SsoResult {
    pub api_key: String,
    /// Cache this and pass it back next time to resume the same session.
    pub connection_token: Option<String>,
}

/// Run the whole sign-in, blocking until the user approves or the wait expires.
///
/// `slug` is the application id issued by Nexus Mods. `previous_token` resumes a
/// session from an earlier run when available.
pub fn sign_in(
    slug: &str,
    previous_token: Option<&str>,
    observer: &dyn SsoObserver,
) -> Result<SsoResult, SsoError> {
    if slug.trim().is_empty() {
        return Err(SsoError::NoApplicationSlug);
    }

    let (mut socket, _) = tungstenite::connect(SSO_WS)
        .map_err(|e| SsoError::Connect(e.to_string()))?;

    let uuid = uuid_v4();
    let request = SsoRequest {
        id: &uuid,
        token: previous_token,
        protocol: 2,
    };
    socket
        .send(tungstenite::Message::Text(
            serde_json::to_string(&request)
                .map_err(|e| SsoError::Protocol(e.to_string()))?,
        ))
        .map_err(|e| SsoError::Connect(e.to_string()))?;

    let deadline = Instant::now() + APPROVAL_TIMEOUT;
    let mut connection_token = previous_token.map(str::to_string);
    let mut opened = false;

    while Instant::now() < deadline {
        let msg = match socket.read() {
            Ok(m) => m,
            Err(e) => return Err(SsoError::Connect(e.to_string())),
        };

        let text = match msg {
            tungstenite::Message::Text(t) => t.to_string(),
            tungstenite::Message::Close(_) => {
                return Err(SsoError::Protocol("the service closed the connection".into()))
            }
            _ => continue,
        };

        let res: SsoResponse =
            serde_json::from_str(&text).map_err(|e| SsoError::Protocol(e.to_string()))?;

        if !res.success {
            return Err(SsoError::Rejected(
                res.error.unwrap_or_else(|| "no reason given".into()),
            ));
        }

        let Some(data) = res.data else { continue };

        if let Some(token) = data.connection_token {
            connection_token = Some(token);
        }

        // The key arrives only after the user approves in the browser.
        if let Some(api_key) = data.api_key {
            let _ = socket.close(None);
            return Ok(SsoResult {
                api_key,
                connection_token,
            });
        }

        // Once the session exists, send the user to approve it.
        if !opened {
            opened = true;
            observer.awaiting_approval(&approval_url(&uuid, slug));
        }
    }

    let _ = socket.close(None);
    Err(SsoError::TimedOut)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn uuid_looks_like_a_v4_uuid() {
        let u = uuid_v4();
        assert_eq!(u.len(), 36);
        let parts: Vec<&str> = u.split('-').collect();
        assert_eq!(
            parts.iter().map(|p| p.len()).collect::<Vec<_>>(),
            vec![8, 4, 4, 4, 12]
        );
        assert!(parts[2].starts_with('4'), "version nibble must be 4");
        assert!(
            ['8', '9', 'a', 'b'].contains(&parts[3].chars().next().unwrap()),
            "variant nibble must be one of 8, 9, a, b"
        );
        assert!(u.chars().all(|c| c.is_ascii_hexdigit() || c == '-'));
    }

    #[test]
    fn uuids_are_not_repeated() {
        let a = uuid_v4();
        let b = uuid_v4();
        assert_ne!(a, b);
    }

    #[test]
    fn approval_url_carries_the_session_and_application() {
        let u = approval_url("abc-123", "apocrypha");
        assert_eq!(
            u,
            "https://www.nexusmods.com/sso?id=abc-123&application=apocrypha"
        );
    }

    #[test]
    fn signing_in_without_a_slug_fails_before_touching_the_network() {
        struct Noop;
        impl SsoObserver for Noop {
            fn awaiting_approval(&self, _: &str) {
                panic!("must not reach the browser step without an application id");
            }
        }
        assert!(matches!(
            sign_in("", None, &Noop),
            Err(SsoError::NoApplicationSlug)
        ));
        assert!(matches!(
            sign_in("   ", None, &Noop),
            Err(SsoError::NoApplicationSlug)
        ));
    }

    #[test]
    fn the_request_matches_the_documented_shape() {
        let json = serde_json::to_string(&SsoRequest {
            id: "u",
            token: None,
            protocol: 2,
        })
        .unwrap();
        assert!(json.contains("\"protocol\":2"));
        assert!(json.contains("\"token\":null"));
    }
}
